version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always 
    ports: 
      - 3305:3306
    environment:
      MYSQL_ROOT_PASSWORD: example 
      MYSQL_USER: user 
      MYSQL_PASSWORD: password 
      MYSQL_DATABASE: books

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080 

  redis:
    image: redis 
    restart: always 
    ports: 
      - 6378:6379
